import { StyleSheet } from "react-native";
import { Font } from "./font";
import { Colors } from "./colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: `center`,
  },
  createProductScreenContainer: {
    justifyContent: `space-evenly`,
    alignItems: `center`,
  },
  productListScreenContainer: {
    flexDirection: `row`,
    flexGrow: 1,
    flexWrap: `wrap`,
    justifyContent: `space-evenly`,
    alignItems: `center`,
    borderColor: Colors.BLACK,
    borderWidth: 1,
    marginVertical: 5,
    width: `95%`,
  },
  centerContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  centerContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    textAlign: "center",
    fontSize: Font.HEADER,
    fontWeight: 700,
    padding: 5,
  },
  loginContainer: {
    marginTop: 10,
    gap: 20,
    justifyContent: "center",
  },
  // textInput: {
  //   width: 300,
  //   padding: 12,
  //   borderWidth: 2,
  //   borderRadius: 10,
  //   borderColor: Colors.OFF_WHITE_DARK,
  // },
  primaryBtn: {
    alignItems: "center",
    backgroundColor: Colors.PRIMARY,
    borderRadius: 10,
  },
  primaryBtnText: {
    color: Colors.WHITE,
    padding: 10,
    fontSize: 18,
  },
  tertiaryBtn: {
    alignItems: "center",
  },
  tertiaryBtnText: {
    alignItems: "center",
    color: Colors.GREY,
  },
  textInput: {
    height: 50,
    fontSize: Font.TEXT1,
    borderColor: Colors.BLACK,
    borderWidth: 1,
    alignContent: `center`,
    alignItems: `center`,
    // textAlign: `center`,
    // textAlignVertical: `center`,
    width: `70%`,
  },
  dropdown: {
    fontSize: Font.TEXT1,
    width: `70%`,
    height: 50,
    borderWidth: 1,
    borderColor: Colors.BLACK,
  },
  dropdown: {
    fontSize: Font.TEXT1,
    width: `70%`,
    height: 50,
    borderWidth: 1,
    borderColor: Colors.BLACK,
  },
  productDetailsTitle: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: 700,
    padding: 10,
  },
  productDetailsCategory: {
    textAlign: "center",
    fontSize: 15,
    fontWeight: 600,
    padding: 5,
  },
  productDetailsDescriptionTitle: {
    textAlign: "flex-start",
    fontSize: 13,
    fontWeight: 600,
  },
  productDetailsDescription: {
    textAlign: "flex-start",
    fontSize: 13,
    fontWeight: 400,
  },
  productDetailsPrice: {
    textAlign: "center",
    fontSize: 15,
    fontWeight: 600,
    padding: 10,
  },
  productDetailsDescriptionView: {
    padding: 10,
    margin: 10,
    borderWidth: 1,
    borderColor: Colors.OFF_WHITE_DARKER,
    borderRadius: 25,
    backgroundColor: Colors.BACKGROUND,
    alignItems: "stretch",
    width: "95%",
    maxHeight: "22%",
  },
  productDetailsQRCodeView: {
    width: 150,
    height: 150,
    padding: 8,
    marginTop: "5%",
    borderWidth: 1,
    borderColor: Colors.OFF_WHITE_DARKER,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  closeButton: {
    position: 'absolute',
    bottom: "40%",
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    left: 0,
    right: 0,
  },
  scanMoreView: {
    position: 'absolute',
    bottom: "20%",
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  loadingScreen: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  imagePickerContainer: {
    width: "70%", 
    alignItems: "center",
  },
  imagePickerButton: {
    width: "20%",
  },
  imagePreview: {
    height: 200, 
    width: "100%",
  },
  productListScreenCardImage: {
    flex: 1,
    resizeMode: "contain",
  },
});
